{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-paco
  version: {{ version|replace("-", "_") }}

source:
  fn: paco_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/paco_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paco/paco_{{ version }}.tar.gz
  sha256: 6f47bccb5c69b9154312c42e7b7e8cafaa2658422a666c0402a98b9064baa5c2

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-plyr
    - r-vegan >=2.2_0
  run:
    - r-base
    - r-plyr
    - r-vegan >=2.2_0

test:
  commands:
    - $R -e "library('paco')"           # [not win]
    - "\"%R%\" -e \"library('paco')\""  # [win]

about:
  home: http://www.uv.es/cophylpaco/
  license: MIT
  summary: Procrustes analyses to infer co-phylogenetic matching between pairs of (ultrametric)
    phylogenetic trees.
  license_family: MIT

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
