{% set version = "0.4.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-paco
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/paco_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paco/paco_{{ version }}.tar.gz
  sha256: 6d1f6270cc8eea4064d26696c463b3e19a63a94494c6bedbd2a71d575873025c

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-ape
    - r-plyr
    - r-vegan >=2.2_0
  run:
    - r-base
    - r-ape
    - r-plyr
    - r-vegan >=2.2_0

test:
  commands:
    - $R -e "library('paco')"           # [not win]
    - "\"%R%\" -e \"library('paco')\""  # [win]

about:
  home: http://www.uv.es/cophylpaco/
  license: MIT
  summary: Procrustes analyses to infer co-phylogenetic matching between pairs of (ultrametric) phylogenetic trees.
  license_family: MIT

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
extra:
  recipe-maintainers:
    - nick-youngblut
    - conda-forge/r

# Package: paco
# Version: 0.4.1
# Date: 2019-05-20
# Title: Procrustes Application to Cophylogenetic Analysis
# Description: Procrustes analyses to infer co-phylogenetic matching between pairs of (ultrametric) phylogenetic trees.
# Author: Juan Antonio Balbuena <j.a.balbuena@uv.es>, Timothee Poisot <tim@poisotlab.io>, Matthew Hutchinson <matthewhutchinson15@gmail.com>, Fernando Cagua <fernando@cagua.co>
# Maintainer: Matthew Hutchinson <matthewhutchinson15@gmail.com>
# Depends: R (>= 3.0.0)
# Imports: vegan (>= 2.2-0), ape, plyr
# Suggests: testthat
# Note: The current version (0.4.1) fixes an issue in the add_pcoord function where negative eigenvalues were left uncorrected when the user specified that a correction be applied.
# License: MIT + file LICENSE
# URL: http://www.uv.es/cophylpaco/
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-05-20 18:26:55 UTC; matthew
# Repository: CRAN
# Date/Publication: 2019-05-20 18:50:06 UTC
