appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ac3zsB/JKb/rrfZxR3c2z4JnyQj3UwSL/mOO/4jhDpgbe015dqrYvVi1FRc8FfvoouAr91HeXDX6OgtKofD0ELAf3R71DnIMvuoob+UTUZ2tiLNYVnR/ijf+Iwb/7z5H2+MbsIf9caHETS7R4ZZ1UyVXAsI9gqZ5j1qEbkyauDBXyr5SD19YNk8rQJQZiScbwLIkhL/2seowtWPy/Kv4HpOlLFbmx43TYYl/0aySzmM38OMcn8zZ0EFJFiOWrHxgIXJNcI63pboGRuL/DBZAmv6NzjEg+Me7WDcQW9i7QwYc+WhYrT61KjTwDhfgjt2ia28fnktQnmswqqgswZMEW53mOMGVtkn4sj/UErvDtn7UUHEMPiCG9YlbqOB20i/5hdWm4BoWCTn65jSnIx40Nkf7pl6mZfAEteuwWwDxvMgEBGvmw5CftSPUqdbJg2Gsvxnkpdha/h800F2v6YeOdKTaOCr6naDu9JPvVaWAq8Z9mXM7PiOif2wS9Jub1L+MnXF0Q8tqEj+gW5jusBzJkFzlioRO2pT7f+7LiZnMiviw0yYLx9SZ3llUkPqOcTw8dHKcTxNvF0mPh6aho86S7K+fUU9sKt9Jp2+r9iXzokcLPZTZ5YhvRBtWxjZROu3j7xsVyXo4Ub8y8av9n4Ot44wqFH56EX+uhaP76bDDkM8=}
