travis:
  secure:
    BINSTAR_TOKEN: JltCFdXG7PhPPbMlDwlV3w77QChgxnI3r4rXjAXYIdjwy0/hCYWAodexQKhtQJdUAfcIEyw/5S1S9aReIr2Gw2Y1M0XOYfjh7P6oFhPGYgPwql1wcoZ/DBWPpWnGWZVhpJ/xRk4j0J4m7Fnd3Ng9vBvx4sV/SeS5ZX6wQT2GRsAeInVz/bluLuen/+2TdKcItKNv1wLdcrbt6cbo+sP06R9VHJd2tfz7YwsimrvglPtyh3z0pvpfnSDKYZWV83Ee89cxaWuUCBYDeUsp0b9BEvU4D59v5t78vZ+uZIlUiZsG72zjBa4iPCqiT08SANuO4qy4eUTCVAuJXog8QbLfQtZ/WAa7AixRdOOJ+c8k/aCx2cFtHg4LEaQVBKRSIm4B9K5dt9Lqc1UK235/+Bwkcn1M+ig8V+DHqy9ZsEnQ3oAdYwQO6GCxXP9eCBe3Q2RSzFsLXqJv7f/hRQhNzenEBrK1TrzaORbmsXb3K43b64s1SaRQQSzrCe+ikxBtw2G+zrwhBL5T4Ndi069txApzC8yLK/CngeOD+NPmEhlI1KXSCLQM3LumoztvwiA9MGFXlpu0xG/ZjPcpcXcSv7v04CqSO8Vqy4TqJHTesRUoN/U8zQrSE40Brif4JOrH3w8+IJH1MOFxyoCXtE9nnEIlule96CjaUL/m5WZnWp5+VI4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
